apiVersion: apps/v1
kind: Deployment
metadata:
  name: wilsoooonnnn-03-to-scall
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: ubuntu:latest

