apiVersion: apps/v1
kind: Deployment
metadata:
  name: wilsoooonnnn-03-rolling-update
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: ubuntu:latest
