apiVersion: v1
kind: Pod
metadata:
  name: wilsoooonnnn-03-liveness-probe
spec:
  containers:
  - image: knrt10/kubia-unhealthy
    name: kubia
    livenessProbe:
      httpGet:
        path:
        port: 8080  
