apiVersion: v1
kind: Pod
metadata:
  name: wilsoooonnnn-03-with-volume
spec:
  containers:
  - name: ubuntu-with-vol
    image: ubuntu
    volumeMounts:
    - mountPath: /data
      name: my-volume
  volumes:
  - name: my-volume
    emptyDir: {}
