FOLDER_PATH = "~/linuxcode/kuliah/tka/praktikum/modul1/soal3"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "2048"
  end

  config.vm.provision "file", source: FOLDER_PATH + "/conf", destination: "~/" 

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y bind9 squid

    sudo cp /home/vagrant/conf/bind/db.tka-c3.local /etc/bind
    sudo cp /home/vagrant/conf/bind/named.conf.local /etc/bind
    sudo cp /home/vagrant/conf/squid/squid.conf /etc/squid
    sudo cp /home/vagrant/conf/resolve.conf /etc/

    sudo systemctl restart bind9
    sudo systemctl restart squid
  SHELL

end
