apiVersion: v1
kind: Pod
metadata:
  name: wilsoooonnnn-03-secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: myimage:latest
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
  restartPolicy: Never
