version: "3.3"


networks:
  api:


services:
  backend-api:
    build:
      context: ./backend
    ports:
      - 8000:8000
      - 3309:3306
    expose:
      - 8000
      - 3306
    restart: always
    env_file: ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    networks:
      - api
    

  frontend-app:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: always
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - api
