apiVersion: v1
kind: Pod
metadata:
  name: wilsoooonnnn-03-with-data-pod
spec:
  containers:
  - name: mycontainer
    image: ubuntu
    env:
      - name: MY_KEY
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: mykey
